services:
  - type: web
    name: rename-bot-2gb
    env: python
    plan: free
    repo: https://github.com/JishuDeveloper/Rename-Bot-4GB
    branch: metadata
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: START_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: WEBHOOK
        value: True
      - key: PORT
        value: 10000